### ISSUE TITLE
Move doc to wiki - Final review

### ISSUE THREAD

**Issue by esthertrigo** [sngular/kloadgen#207]
### Summary

After final content approval (issues #196 and #201), the files should be moved to the wiki (related to issue #199). After that, a final proofreading takes place, where also minor issues can be fixed.

### Tasks

- [x] Final proofreading (grammar/style)
- [x] Screenshots update as per changes in sampler and config element names, depends on #272
- [x] Check no reference to change log exists
- [x] Check no reference to CONTRIBUTING exists/CONTRIBUTING is created
- [x] Check whether _Sidebar works as expected
- [x] Links
- [x] Images
- [x] Apply developers' comments
