### ISSUE TITLE
[Documentation Issue]: Add screenshots to Knowledge Center module

### ISSUE THREAD

**Issue by OlgaCalderon** [sngular/kloadgen#358]
## Summary

As part of the final review process of the documentation, it is necessary to add some screenshots to the "How to run" page inside the Knowledge Center module. This will help the user to follow the steps easily.

## Tasks

- [ ] Attach screenshots to the documentation BEFORE the steps mentioned. It would be preferable if the screenshots represent numbers and each step refers to them.

### Have you found it in the docs folder?

- [X] I have already checked the docs folder

### Have you checked whether this issue is already being taken care of?

- [X] I have already checked whether this issue is being taken care of.
